[General]
cdAuto=true
cddbHost=gnudb.gnudb.org
cddbPort=80
composerGenres=@Invalid()
contextAlwaysCollapsed=false
contextAutoScroll=false
contextBackdrop=0
contextBackdropBlur=0
contextBackdropFile=
contextBackdropOpacity=15
contextDarkBackground=false
contextSplitterState="@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x3\0\0\x1,\0\0\x1,\0\0\x1,\x1\0\0\0\0\x1\0\0\0\x1\0)"
contextSwitchTime=0
contextTrackView=0
coverFilename=
cueSupport=ignore
currentConnection=-
fetchCovers=false
forceSingleClick=true
hiddenPages=PlayQueuePage, PlaylistsPage, OnlineServicesPage, DevicesPage
hiddenStreamCategories=@Invalid()
ignorePrefixes=The
infoTooltips=true
inhibitSuspend=false
lang=
lyricProviders=azlyrics.com, chartlyrics.com, lyrics.wikia.com
mainWindowCollapsedSize=@Size(1035 62)
mainWindowSize=@Size(1113 876)
maximized=false
minimiseOnClose=false
mpris=true
page=LibraryPage
paranoiaFull=true
paranoiaNeverSkip=true
paranoiaOffset=0
playQueueAutoExpand=true
playQueueBackground=1
playQueueBackgroundBlur=0
playQueueBackgroundFile=
playQueueBackgroundOpacity=15
playQueueConfirmClear=false
playQueueScroll=true
playQueueSearch=true
playQueueStartClosed=false
playQueueView=grouped
playStream=false
responsiveSidebar=true
showCoverWidget=true
showDeleteAction=false
showFullScreen=false
showMenubar=false
showPlaylist=true
showPopups=false
showRatingWidget=false
showStopButton=false
showTechnicalInfo=true
showTimeRemaining=false
sidebar=290
singleTracksFolders=@Invalid()
splitterAutoHide=false
splitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x2\xea\0\0\x1n\x1\0\0\0\x1\x1\0\0\0\x1\0)
startupState=show
stopFadeDuration=500
stopOnExit=true
storeCoversInMpdDir=false
storeLyricsInMpdDir=false
style=
useCddb=false
useOriginalYear=false
useSystemTray=false
version=2.4.2
volumeStep=5
wikipediaIntroOnly=true

[AlbumView]
fullWidthCover=false

[Connection--]
allowLocalStreaming=true
applyReplayGain=true
autoUpdate=false
dir=~/stuff/Music
host=/home/nero/.local/share/cantata/mpd/socket
passwd=
port=6600
replayGain=off
streamUrl=

[CoverDialog]
enabledProviders=63
size=@Size(452 496)

[DevicesPage]
gridZoom=100
searchActive=false
viewMode=simpletree

[DynamicPlaylistsPage]
gridZoom=100
searchActive=false
viewMode=list

[FolderPage]
currentPage=

[HttpStream]
volume=50

[LibraryPage]
album\gridZoom=100
album\searchActive=false
album\viewMode=icontop
albumSort=aryral
artist\gridZoom=100
artist\searchActive=false
artist\viewMode=icontop
artistImages=false
grouping=album
librarySort=year

[MpdBrowsePage]
gridZoom=100
searchActive=false
viewMode=detailedtree

[OnlineServicesPage]
currentPage=

[PlayQueuePage]
searchActive=false

[PlaylistsPage]
currentPage=

[PodcastWidget]
gridZoom=100
searchActive=false
viewMode=detailedtree

[PreferencesDialog]
size=@Size(897 721)

[Proxy]
hostname=
mode=0
password=
port=8080
type=3
username=

[SearchPage]
gridZoom=100
searchActive=false
searchCategory=artist
viewMode=list

[Shortcuts-cantata]
playpausetrack=Pause

[SmartPlaylistsPage]
gridZoom=100
searchActive=false
viewMode=list

[StoredPlaylistsPage]
gridZoom=100
searchActive=false
startClosed=true
viewMode=detailedtree

[StreamsBrowsePage]
gridZoom=100
searchActive=false
viewMode=detailedtree

[TrackOrganiser]
size=@Size(800 500)

[VolumeControl]
control=mpd

[jamendo]
albumSort=album
gridZoom=100
grouping=genre
librarySort=year
searchActive=false
viewMode=detailedtree

[localbrowsehome]
gridZoom=100
searchActive=false
viewMode=simpletree

[localbrowseroot]
gridZoom=100
searchActive=false
viewMode=simpletree

[magnatune]
albumSort=album
gridZoom=100
grouping=genre
librarySort=year
searchActive=false
viewMode=detailedtree
