backend = "glx";
glx-no-rebind-pixmap = false;

vsync = true;
refresh-rate = 60;

shadow = false;

fading = true;
fade-in-step = 0.045;
fade-out-step = 0.045;

log-level = "warn";

frame-opacity = 0.5;
