--ozone-platform-hint=auto
--js-flags=--jitless
--enable-system-notifications
--extension-mime-request-handling=always-prompt-for-install
--fingerprinting-canvas-image-data-noise
--fingerprinting-canvas-measuretext-noise
--fingerprinting-client-rects-noise
--popups-to-tabs
--custom-ntp=https://h.ico.wf
--disable-sharing-hub
--hide-sidepanel-button
--show-avatar-button=never
--enable-features=VaapiVideoDecoder,VaapiVideoEncoder
--disable-features=UseChromeOSDirectVideoDecoder
